services:
  db:
    image: postgres:13
    container_name: fruit_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fruitdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fruitdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: fruit_backend
    build: ./backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/fruitdb"
      OIDC_ISSUER_URL_INTERNAL: http://authserver:8082
      OIDC_ISSUER_URL_EXTERNAL: "https://auth.wgd.example.com:8000"
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
    depends_on:
      db:
        condition: service_healthy
      authserver:
        condition: service_started

  frontend:
    container_name: fruit_frontend
    image: nginx:alpine
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

  authserver:
    container_name: fruit-shop-authserver
    build: ./authserver
    ports:
      - "8082:8082"
