services:
  db:
    image: fruit/shop-db:1.0.0
    container_name: fruit-shop-db
    build: ./db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fruitdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fruitdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: fruit/shop-backend:1.0.0
    container_name: fruit-shop-backend
    build: ./backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/fruitdb"
      OIDC_ISSUER_URL_INTERNAL: http://authserver:8082
      OIDC_ISSUER_URL_EXTERNAL: "https://auth.sr.example.com:8000"
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      authserver:
        condition: service_started

  frontend:
    image: nginx:alpine
    container_name: fruit-shop-frontend
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  authserver:
    image: fruit/shop-authserver:1.0.0
    container_name: fruit-shop-authserver
    build: ./authserver
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
